---
title: "EVE Project"
author: "Jacob Wert"
date: "May 17, 2018"
output: html_document
---
#disease vs animal species/kind frequency

```{r}
library(tidyverse)
library(tidyr)

CAHFSData <- read.csv("/home/ubuntu/EVEProject/Data.csv")
colnames(CAHFSData) <- c("Pathogen", "Date", "Species", "County", "Age", "Tissue")
CAHFSData <- mutate_all(CAHFSData, funs(toupper))

#Import the data set and asssign column names to the data set.
```

```{r}
CAHFSPositiveVirus <- subset(CAHFSData, Pathogen == "POSITIVE ADENOVIRUS" | Pathogen == "POSITIVE BIRNAVIRUS" | Pathogen == "POSITIVE REOVIRUS" | Pathogen == "POSITIVE ROTAVIRUS")
#Subset CAHFS data set to only include the data positive for Adeno, Birna, Reo and Rotavirus
```

```{r}
Counties <- table(CAHFSData$County)
Counties
Species <- table(CAHFSData$Species)
Species
Pathogens <- table(CAHFSData$Pathogen)
Pathogens
#Count the frequency of the counties
```

```{r}
NegativePositiveViruses <- subset(CAHFSData, Pathogen == "POSITIVE ADENOVIRUS" | Pathogen == "POSITIVE BIRNAVIRUS" | Pathogen == "POSITIVE CALICIVIRUS" | Pathogen == "POSITIVE CORONAVIRUS" | Pathogen == "POSITIVE ENTEROVIRUS" | Pathogen == "POSITIVE HERPESVIRUS" | Pathogen == "POSITIVE PARAMYXOVIRUS" | Pathogen == "POSITIVE PARAPOXVIRUS" | Pathogen == "POSITIVE POX VIRUS" | Pathogen == "POSITIVE REOVIRUS" | Pathogen == "POSITIVE ROTAVIRUS" | Pathogen == "NEGATIVE")

PositiveViruses <- subset(CAHFSData, Pathogen == "POSITIVE ADENOVIRUS" | Pathogen == "POSITIVE BIRNAVIRUS" | Pathogen == "POSITIVE CALICIVIRUS" | Pathogen == "POSITIVE CORONAVIRUS" | Pathogen == "POSITIVE ENTEROVIRUS" | Pathogen == "POSITIVE HERPESVIRUS" | Pathogen == "POSITIVE PARAMYXOVIRUS" | Pathogen == "POSITIVE PARAPOXVIRUS" | Pathogen == "POSITIVE POX VIRUS" | Pathogen == "POSITIVE REOVIRUS" | Pathogen == "POSITIVE ROTAVIRUS")
#Subset the data to only include positive virus

NegativePositiveViruses %>% ggplot(aes(x = Pathogen, color = Pathogen, fill = Pathogen)) + 
    geom_bar() + 
    theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
    ylab("Number of Infections") +
    ggtitle("All Positive Viruses and Negative Results") +
    geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black")

PositiveViruses %>% ggplot(aes(x = Pathogen, color = Pathogen, fill = Pathogen)) + 
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ylab("Number of Infections") +
  ggtitle("All Positive Viruses") +
  geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black")

MostCommonSpecies <- subset(PositiveViruses, Species == "BOVINE" | Species == "CHICKEN" | Species == "TURKEY")
MostCommonSpecies %>% ggplot(aes(x = Pathogen, color = Pathogen, fill = Pathogen)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ylab("Number of Infections") +
  ggtitle("All Viruses from the Most Common Species") +
  geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black")

#Subset the data to the most common species, with a histogram of the data
```

```{r}
Turkey <- subset(CAHFSData, Species == 'TURKEY')
Chicken <- subset(CAHFSData, Species == 'CHICKEN')
Bovine <- subset(CAHFSData, Species == 'BOVINE')
#Subset the original data by the most prevelant species.
```

```{r}
TurkeyPositive <- subset(Turkey, Pathogen != "NEGATIVE")

TurkeyPositiveViruses <- subset(TurkeyPositive, Pathogen == "POSITIVE ADENOVIRUS" | Pathogen == "POSITIVE BIRNAVIRUS" | Pathogen == "POSITIVE REOVIRUS" | Pathogen == "POSITIVE ROTAVIRUS")
#Subset Turkey data to just have the positive samples for Adenovirus, Birnavirus, Reovirus and Reovirus
```

```{r}
TurkeyPositiveViruses %>% ggplot(aes(x = County, color = Pathogen)) + 
 geom_bar(aes(fill = Pathogen)) +
 theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
 ylab("Number of Viruses By County") +
 geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black") +
 ggtitle("Turkey Viruses by County")
#Check the virus subset for which county the virus is most common in

TurkeyPositiveViruses %>% ggplot(aes(x = Pathogen, color = Pathogen, fill = Pathogen)) + 
  stat_count() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of Positive Infections") + 
  xlab("Pathogen Name") +
  ggtitle("Most Common Positives - Turkey") +
  geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black")
#Histogram of frequency of confirmed cases of Adeno, Birna, Reo and Rotavirus

```

```{r}
TurkeyPositiveFresno <- subset(TurkeyPositive, County == "FRESNO")
TurkeyPositiveViruses %>% ggplot(aes(x = Pathogen, y = Tissue)) + 
 geom_point() +
 theme(axis.text.x = element_text(angle = 45, hjust = 1)) + #Rotates x-axis element text for easier reading
 ggtitle("Tissue Type vs Pathogen in Turkey")
  
#Checking Fresno samples for what tissue the virus is most prevelant in
```

```{r}
ChickenPositive <- subset(Chicken, Pathogen != "NEGATIVE")

ChickenPositiveViruses <- subset(ChickenPositive, Pathogen == "POSITIVE ADENOVIRUS" | Pathogen == "POSITIVE BIRNAVIRUS" | Pathogen == "POSITIVE REOVIRUS" | Pathogen == "POSITIVE ROTAVIRUS" | Pathogen == "POSITIVE CALICIVIRUS" | Pathogen == "POSITIVE HERPESVIRUS" | Pathogen == "POSITIVE POX VIRUS")
#Subset Chicken data to just have the positive viruses
```

```{r}
ChickenPositiveViruses %>% ggplot(aes(x = County, color = Pathogen)) + 
  geom_bar(aes(fill = Pathogen)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of Viruses By County") +
  geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black") +
  ggtitle("Chicken Viruses by County")
#Check the virus subset for which county the virus is most common in
  
ChickenPositiveViruses %>% ggplot(aes(x = Pathogen, color = Pathogen, fill = Pathogen)) + 
    stat_count() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylab("Number of Positive Infections") + 
    xlab("Pathogen Name") +
    ggtitle("Most Common Positives - Chicken") +
    geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black")
#Histogram of frequency of confirmed cases of Adeno, Birna, Reo and Rotavirus
```

```{r}
BovinePositive <- subset(Bovine, Pathogen != "NEGATIVE")
BovinePositiveViruses <- subset(BovinePositive, Pathogen == "POSITIVE CORONAVIRUS" | Pathogen == "POSITIVE PARAPOXVIRUS" | Pathogen == "POSITIVE POX VIRUS" | Pathogen == "POSITIVE ROTAVIRUS")
```

```{r}
BovinePositiveViruses %>% ggplot(aes(x = County, color = Pathogen)) + 
  geom_bar(aes(fill = Pathogen)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of Viruses By County") +
  geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black") +
  ggtitle("Bovine Viruses by County")
#Check the virus subset for which county the virus is most common in
  
BovinePositiveViruses %>% ggplot(aes(x = Pathogen, color = Pathogen, fill = Pathogen)) + 
    stat_count() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylab("Number of Positive Infections") + 
    xlab("Pathogen Name") +
    ggtitle("Most Common Positives - Bovine") +
    geom_text(stat='count', aes(label=..count..), vjust = -0.25, color = "Black")
#Histogram of frequency of confirmed cases
```